import type { Lead, QuickResponse, AdminStats } from "@/types/admin";

// Datos mock para el panel de administración
export const mockLeads: Lead[] = [
  {
    id: "1",
    name: "María González",
    whatsapp: "+34612345678",
    country_code: "+34",
    problem: "Problemas de relación con mi pareja",
    cards_selected: ["La Emperatriz", "Los Enamorados"],
    answers: { answer1: "Sí", answer2: "A veces" },
    status: "nuevo",
    stage: "lead",
    last_interaction_at: new Date().toISOString(),
    notes: "",
    is_favorite: false,
    created_at: new Date().toISOString(),
    deleted_at: null,
    assigned_to: null,
    priority: null,
    conversion_date: null,
    tags: [],
  },
  {
    id: "2",
    name: "Carlos Rodríguez",
    whatsapp: "+52155512345",
    country_code: "+52",
    problem: "Indecisión sobre cambio de carrera",
    cards_selected: ["El Sol", "La Estrella"],
    answers: { answer1: "No", answer2: "Nunca" },
    status: "enConversacion",
    stage: "qualified",
    last_interaction_at: new Date().toISOString(),
    notes: "",
    is_favorite: true,
    created_at: new Date().toISOString(),
    deleted_at: null,
    assigned_to: null,
    priority: null,
    conversion_date: null,
    tags: [],
  },
  {
    id: "3",
    name: "Ana Martínez",
    whatsapp: "+56912345678",
    country_code: "+56",
    problem: "Busco claridad espiritual",
    cards_selected: ["La Sacerdotisa"],
    answers: { answer1: "Sí", answer2: "Siempre" },
    status: "clienteCaliente",
    stage: "proposal",
    last_interaction_at: new Date().toISOString(),
    notes: "",
    is_favorite: false,
    created_at: new Date().toISOString(),
    deleted_at: null,
    assigned_to: null,
    priority: null,
    conversion_date: null,
    tags: [],
  },
  {
    id: "4",
    name: "Pedro Sánchez",
    whatsapp: "+34623456789",
    country_code: "+34",
    problem: "Problemas económicos",
    cards_selected: ["La Emperatriz", "El Sol"],
    answers: { answer1: "No", answer2: "A veces" },
    status: "nuevo",
    stage: "lead",
    last_interaction_at: new Date().toISOString(),
    notes: "",
    is_favorite: false,
    created_at: new Date().toISOString(),
    deleted_at: null,
    assigned_to: null,
    priority: null,
    conversion_date: null,
    tags: [],
  },
  {
    id: "5",
    name: "Laura Fernández",
    whatsapp: "+52155598765",
    country_code: "+52",
    problem: "Conflictos familiares",
    cards_selected: ["Los Enamorados", "La Sacerdotisa"],
    answers: { answer1: "Sí", answer2: "Nunca" },
    status: "enConversacion",
    stage: "qualified",
    last_interaction_at: new Date().toISOString(),
    notes: "",
    is_favorite: true,
    created_at: new Date().toISOString(),
    deleted_at: null,
    assigned_to: null,
    priority: null,
    conversion_date: null,
    tags: [],
  },
  {
    id: "6",
    name: "Diego López",
    whatsapp: "+56923456789",
    country_code: "+56",
    problem: "Ansiedad y estrés",
    cards_selected: ["La Estrella"],
    answers: { answer1: "No", answer2: "Siempre" },
    status: "cerrado",
    stage: "customer",
    last_interaction_at: new Date().toISOString(),
    notes: "",
    is_favorite: false,
    created_at: new Date().toISOString(),
    deleted_at: null,
    assigned_to: null,
    priority: null,
    conversion_date: null,
    tags: [],
  },
  {
    id: "7",
    name: "Carmen Ruiz",
    whatsapp: "+34634567890",
    country_code: "+34",
    problem: "Orientación espiritual general",
    cards_selected: ["El Sol", "La Emperatriz", "Los Enamorados"],
    answers: { answer1: "Sí", answer2: "A veces" },
    status: "perdido",
    stage: "lost",
    last_interaction_at: new Date().toISOString(),
    notes: "",
    is_favorite: false,
    created_at: new Date().toISOString(),
    deleted_at: null,
    assigned_to: null,
    priority: null,
    conversion_date: null,
    tags: [],
  },
  {
    id: "8",
    name: "Miguel Torres",
    whatsapp: "+52155534567",
    country_code: "+52",
    problem: "Busco respuestas sobre mi futuro",
    cards_selected: ["La Sacerdotisa", "La Estrella"],
    answers: { answer1: "No", answer2: "Nunca" },
    status: "listo",
    stage: "ready",
    last_interaction_at: new Date().toISOString(),
    notes: "",
    is_favorite: true,
    created_at: new Date().toISOString(),
    deleted_at: null,
    assigned_to: null,
    priority: null,
    conversion_date: null,
    tags: [],
  },
  {
    id: "9",
    name: "Isabel García",
    whatsapp: "+56934567890",
    country_code: "+56",
    problem: "Necesito guía en mi vida amorosa",
    cards_selected: ["Los Enamorados"],
    answers: { answer1: "Sí", answer2: "Siempre" },
    status: "nuevo",
    stage: "lead",
    last_interaction_at: new Date().toISOString(),
    notes: "",
    is_favorite: false,
    created_at: new Date().toISOString(),
    deleted_at: null,
    assigned_to: null,
    priority: null,
    conversion_date: null,
    tags: [],
  },
  {
    id: "10",
    name: "Francisco Morales",
    whatsapp: "+34645678901",
    country_code: "+34",
    problem: "Dificultades para tomar decisiones importantes",
    cards_selected: ["El Sol", "La Sacerdotisa"],
    answers: { answer1: "No", answer2: "A veces" },
    status: "enConversacion",
    stage: "qualified",
    last_interaction_at: new Date().toISOString(),
    notes: "",
    is_favorite: false,
    created_at: new Date().toISOString(),
    deleted_at: null,
    assigned_to: null,
    priority: null,
    conversion_date: null,
    tags: [],
  },
  {
    id: "11",
    name: "Rosa Jiménez",
    whatsapp: "+52155545678",
    country_code: "+52",
    problem: "Problemas de salud emocional",
    cards_selected: ["La Emperatriz", "La Estrella"],
    answers: { answer1: "Sí", answer2: "Nunca" },
    status: "clienteCaliente",
    stage: "proposal",
    last_interaction_at: new Date().toISOString(),
    notes: "",
    is_favorite: true,
    created_at: new Date().toISOString(),
    deleted_at: null,
    assigned_to: null,
    priority: null,
    conversion_date: null,
    tags: [],
  },
  {
    id: "12",
    name: "Alberto Castro",
    whatsapp: "+56945678901",
    country_code: "+56",
    problem: "Busco conexión con mi yo interior",
    cards_selected: ["La Sacerdotisa", "El Sol"],
    answers: { answer1: "No", answer2: "Siempre" },
    status: "cerrado",
    stage: "customer",
    last_interaction_at: new Date().toISOString(),
    notes: "",
    is_favorite: false,
    created_at: new Date().toISOString(),
    deleted_at: null,
    assigned_to: null,
    priority: null,
    conversion_date: null,
    tags: [],
  },
  {
    id: "13",
    name: "Elena Navarro",
    whatsapp: "+34656789012",
    country_code: "+34",
    problem: "Necesito claridad sobre mi propósito de vida",
    cards_selected: ["Los Enamorados", "La Estrella", "La Emperatriz"],
    answers: { answer1: "Sí", answer2: "A veces" },
    status: "nuevo",
    stage: "lead",
    last_interaction_at: new Date().toISOString(),
    notes: "",
    is_favorite: false,
    created_at: new Date().toISOString(),
    deleted_at: null,
    assigned_to: null,
    priority: null,
    conversion_date: null,
    tags: [],
  },
];

export const mockQuickResponses: QuickResponse[] = [
  {
    id: "1",
    label: "BIENVENIDA",
    message: "Bienvenido/a al Oráculo. Estoy aquí para guiarte en tu camino espiritual. ¿En qué puedo ayudarte hoy?"
  },
  {
    id: "2",
    label: "CONSULTA TAROT",
    message: "Para realizar la lectura de tarot, necesito saber, ¿cuál es la situación o pregunta principal que deseas explorar?"
  },
  {
    id: "3",
    label: "PRECIO PLAN",
    message: "Ofrecemos consultas personalizadas. El plan básico incluye lectura de tarot + guía espiritual por $49. ¿Te interesa conocer más detalles?"
  },
  {
    id: "4",
    label: "AGENDAR SESIÓN",
    message: "Perfecto, podemos agendar tu sesión espiritual. ¿Qué día y hora te vendría mejor?"
  },
  {
    id: "5",
    label: "CIERRE DE VENTA",
    message: "Las energías están alineadas para tu consulta. Para confirmar tu sesión, necesito que realices el pago. ¿Procedo a enviarte los detalles?"
  },
  {
    id: "6",
    label: "SEGUIMIENTO",
    message: "¿Cómo te has sentido desde nuestra última consulta? ¿Has notado cambios en tu situación?"
  },
  {
    id: "7",
    label: "OFERTA ESPECIAL",
    message: "Esta semana tengo una promoción especial: sesión completa + ritual personalizado con 30% de descuento. ¿Te gustaría aprovecharla?"
  },
  {
    id: "8",
    label: "LIMPIEZA ENERGÉTICA",
    message: "Percibo que necesitas una limpieza energética profunda. Te puedo guiar en un ritual especial. ¿Te interesa?"
  }
];

export const mockStats: AdminStats = {
  totalAlmas: 13,
  clickWA: 2,
  atendidos: 1,
  sinResponder: 12,
  pipeline: {
    nuevo: 32,
    enConversacion: 0,
    clienteCaliente: 0,
    cerrado: 1,
    perdido: 0
  }
};